// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="BLNK,hls_ip_2015_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35tcpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=5.745000,HLS_SYN_LAT=309124,HLS_SYN_TPT=309124,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=326,HLS_SYN_LUT=447}" *)

module BLNK (
        InS_TDATA,
        InS_TKEEP,
        InS_TSTRB,
        InS_TUSER,
        InS_TLAST,
        InS_TID,
        InS_TDEST,
        OutS_TDATA,
        OutS_TKEEP,
        OutS_TSTRB,
        OutS_TUSER,
        OutS_TLAST,
        OutS_TID,
        OutS_TDEST,
        ap_clk,
        ap_rst_n,
        InS_TVALID,
        InS_TREADY,
        OutS_TVALID,
        OutS_TREADY
);

parameter    ap_const_lv24_0 = 24'b000000000000000000000000;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_true = 1'b1;

input  [23:0] InS_TDATA;
input  [2:0] InS_TKEEP;
input  [2:0] InS_TSTRB;
input  [0:0] InS_TUSER;
input  [0:0] InS_TLAST;
input  [0:0] InS_TID;
input  [0:0] InS_TDEST;
output  [23:0] OutS_TDATA;
output  [2:0] OutS_TKEEP;
output  [2:0] OutS_TSTRB;
output  [0:0] OutS_TUSER;
output  [0:0] OutS_TLAST;
output  [0:0] OutS_TID;
output  [0:0] OutS_TDEST;
input   ap_clk;
input   ap_rst_n;
input   InS_TVALID;
output   InS_TREADY;
output   OutS_TVALID;
input   OutS_TREADY;

reg    ap_rst_n_inv;
wire    BLNK_AXIvideo2Mat_24_480_640_32_U0_ap_start;
wire    BLNK_AXIvideo2Mat_24_480_640_32_U0_ap_done;
wire    BLNK_AXIvideo2Mat_24_480_640_32_U0_ap_continue;
wire    BLNK_AXIvideo2Mat_24_480_640_32_U0_ap_idle;
wire    BLNK_AXIvideo2Mat_24_480_640_32_U0_ap_ready;
wire   [23:0] BLNK_AXIvideo2Mat_24_480_640_32_U0_InS_TDATA;
wire    BLNK_AXIvideo2Mat_24_480_640_32_U0_InS_TVALID;
wire    BLNK_AXIvideo2Mat_24_480_640_32_U0_InS_TREADY;
wire   [2:0] BLNK_AXIvideo2Mat_24_480_640_32_U0_InS_TKEEP;
wire   [2:0] BLNK_AXIvideo2Mat_24_480_640_32_U0_InS_TSTRB;
wire   [0:0] BLNK_AXIvideo2Mat_24_480_640_32_U0_InS_TUSER;
wire   [0:0] BLNK_AXIvideo2Mat_24_480_640_32_U0_InS_TLAST;
wire   [0:0] BLNK_AXIvideo2Mat_24_480_640_32_U0_InS_TID;
wire   [0:0] BLNK_AXIvideo2Mat_24_480_640_32_U0_InS_TDEST;
wire   [7:0] BLNK_AXIvideo2Mat_24_480_640_32_U0_img_data_stream_0_V_din;
wire    BLNK_AXIvideo2Mat_24_480_640_32_U0_img_data_stream_0_V_full_n;
wire    BLNK_AXIvideo2Mat_24_480_640_32_U0_img_data_stream_0_V_write;
wire   [7:0] BLNK_AXIvideo2Mat_24_480_640_32_U0_img_data_stream_1_V_din;
wire    BLNK_AXIvideo2Mat_24_480_640_32_U0_img_data_stream_1_V_full_n;
wire    BLNK_AXIvideo2Mat_24_480_640_32_U0_img_data_stream_1_V_write;
wire   [7:0] BLNK_AXIvideo2Mat_24_480_640_32_U0_img_data_stream_2_V_din;
wire    BLNK_AXIvideo2Mat_24_480_640_32_U0_img_data_stream_2_V_full_n;
wire    BLNK_AXIvideo2Mat_24_480_640_32_U0_img_data_stream_2_V_write;
reg    BLNK_Loop_1_proc_U0_ap_start = 1'b0;
wire    BLNK_Loop_1_proc_U0_ap_done;
wire    BLNK_Loop_1_proc_U0_ap_continue;
wire    BLNK_Loop_1_proc_U0_ap_idle;
wire    BLNK_Loop_1_proc_U0_ap_ready;
wire   [7:0] BLNK_Loop_1_proc_U0_img_0_data_stream_0_V_dout;
wire    BLNK_Loop_1_proc_U0_img_0_data_stream_0_V_empty_n;
wire    BLNK_Loop_1_proc_U0_img_0_data_stream_0_V_read;
wire   [7:0] BLNK_Loop_1_proc_U0_img_0_data_stream_1_V_dout;
wire    BLNK_Loop_1_proc_U0_img_0_data_stream_1_V_empty_n;
wire    BLNK_Loop_1_proc_U0_img_0_data_stream_1_V_read;
wire   [7:0] BLNK_Loop_1_proc_U0_img_0_data_stream_2_V_dout;
wire    BLNK_Loop_1_proc_U0_img_0_data_stream_2_V_empty_n;
wire    BLNK_Loop_1_proc_U0_img_0_data_stream_2_V_read;
wire   [7:0] BLNK_Loop_1_proc_U0_img_1_data_stream_0_V_din;
wire    BLNK_Loop_1_proc_U0_img_1_data_stream_0_V_full_n;
wire    BLNK_Loop_1_proc_U0_img_1_data_stream_0_V_write;
wire   [7:0] BLNK_Loop_1_proc_U0_img_1_data_stream_1_V_din;
wire    BLNK_Loop_1_proc_U0_img_1_data_stream_1_V_full_n;
wire    BLNK_Loop_1_proc_U0_img_1_data_stream_1_V_write;
wire   [7:0] BLNK_Loop_1_proc_U0_img_1_data_stream_2_V_din;
wire    BLNK_Loop_1_proc_U0_img_1_data_stream_2_V_full_n;
wire    BLNK_Loop_1_proc_U0_img_1_data_stream_2_V_write;
reg    BLNK_Mat2AXIvideo_24_480_640_32_U0_ap_start = 1'b0;
wire    BLNK_Mat2AXIvideo_24_480_640_32_U0_ap_done;
wire    BLNK_Mat2AXIvideo_24_480_640_32_U0_ap_continue;
wire    BLNK_Mat2AXIvideo_24_480_640_32_U0_ap_idle;
wire    BLNK_Mat2AXIvideo_24_480_640_32_U0_ap_ready;
wire   [7:0] BLNK_Mat2AXIvideo_24_480_640_32_U0_img_data_stream_0_V_dout;
wire    BLNK_Mat2AXIvideo_24_480_640_32_U0_img_data_stream_0_V_empty_n;
wire    BLNK_Mat2AXIvideo_24_480_640_32_U0_img_data_stream_0_V_read;
wire   [7:0] BLNK_Mat2AXIvideo_24_480_640_32_U0_img_data_stream_1_V_dout;
wire    BLNK_Mat2AXIvideo_24_480_640_32_U0_img_data_stream_1_V_empty_n;
wire    BLNK_Mat2AXIvideo_24_480_640_32_U0_img_data_stream_1_V_read;
wire   [7:0] BLNK_Mat2AXIvideo_24_480_640_32_U0_img_data_stream_2_V_dout;
wire    BLNK_Mat2AXIvideo_24_480_640_32_U0_img_data_stream_2_V_empty_n;
wire    BLNK_Mat2AXIvideo_24_480_640_32_U0_img_data_stream_2_V_read;
wire   [23:0] BLNK_Mat2AXIvideo_24_480_640_32_U0_OutS_TDATA;
wire    BLNK_Mat2AXIvideo_24_480_640_32_U0_OutS_TVALID;
wire    BLNK_Mat2AXIvideo_24_480_640_32_U0_OutS_TREADY;
wire   [2:0] BLNK_Mat2AXIvideo_24_480_640_32_U0_OutS_TKEEP;
wire   [2:0] BLNK_Mat2AXIvideo_24_480_640_32_U0_OutS_TSTRB;
wire   [0:0] BLNK_Mat2AXIvideo_24_480_640_32_U0_OutS_TUSER;
wire   [0:0] BLNK_Mat2AXIvideo_24_480_640_32_U0_OutS_TLAST;
wire   [0:0] BLNK_Mat2AXIvideo_24_480_640_32_U0_OutS_TID;
wire   [0:0] BLNK_Mat2AXIvideo_24_480_640_32_U0_OutS_TDEST;
wire    ap_sig_hs_continue;
wire    img_0_data_stream_0_V_U_ap_dummy_ce;
wire   [7:0] img_0_data_stream_0_V_din;
wire    img_0_data_stream_0_V_full_n;
wire    img_0_data_stream_0_V_write;
wire   [7:0] img_0_data_stream_0_V_dout;
wire    img_0_data_stream_0_V_empty_n;
wire    img_0_data_stream_0_V_read;
wire    img_0_data_stream_1_V_U_ap_dummy_ce;
wire   [7:0] img_0_data_stream_1_V_din;
wire    img_0_data_stream_1_V_full_n;
wire    img_0_data_stream_1_V_write;
wire   [7:0] img_0_data_stream_1_V_dout;
wire    img_0_data_stream_1_V_empty_n;
wire    img_0_data_stream_1_V_read;
wire    img_0_data_stream_2_V_U_ap_dummy_ce;
wire   [7:0] img_0_data_stream_2_V_din;
wire    img_0_data_stream_2_V_full_n;
wire    img_0_data_stream_2_V_write;
wire   [7:0] img_0_data_stream_2_V_dout;
wire    img_0_data_stream_2_V_empty_n;
wire    img_0_data_stream_2_V_read;
wire    img_1_data_stream_0_V_U_ap_dummy_ce;
wire   [7:0] img_1_data_stream_0_V_din;
wire    img_1_data_stream_0_V_full_n;
wire    img_1_data_stream_0_V_write;
wire   [7:0] img_1_data_stream_0_V_dout;
wire    img_1_data_stream_0_V_empty_n;
wire    img_1_data_stream_0_V_read;
wire    img_1_data_stream_1_V_U_ap_dummy_ce;
wire   [7:0] img_1_data_stream_1_V_din;
wire    img_1_data_stream_1_V_full_n;
wire    img_1_data_stream_1_V_write;
wire   [7:0] img_1_data_stream_1_V_dout;
wire    img_1_data_stream_1_V_empty_n;
wire    img_1_data_stream_1_V_read;
wire    img_1_data_stream_2_V_U_ap_dummy_ce;
wire   [7:0] img_1_data_stream_2_V_din;
wire    img_1_data_stream_2_V_full_n;
wire    img_1_data_stream_2_V_write;
wire   [7:0] img_1_data_stream_2_V_dout;
wire    img_1_data_stream_2_V_empty_n;
wire    img_1_data_stream_2_V_read;
reg    ap_CS;
reg    ap_sig_hs_done;


BLNK_AXIvideo2Mat_24_480_640_32_s BLNK_AXIvideo2Mat_24_480_640_32_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( BLNK_AXIvideo2Mat_24_480_640_32_U0_ap_start ),
    .ap_done( BLNK_AXIvideo2Mat_24_480_640_32_U0_ap_done ),
    .ap_continue( BLNK_AXIvideo2Mat_24_480_640_32_U0_ap_continue ),
    .ap_idle( BLNK_AXIvideo2Mat_24_480_640_32_U0_ap_idle ),
    .ap_ready( BLNK_AXIvideo2Mat_24_480_640_32_U0_ap_ready ),
    .InS_TDATA( BLNK_AXIvideo2Mat_24_480_640_32_U0_InS_TDATA ),
    .InS_TVALID( BLNK_AXIvideo2Mat_24_480_640_32_U0_InS_TVALID ),
    .InS_TREADY( BLNK_AXIvideo2Mat_24_480_640_32_U0_InS_TREADY ),
    .InS_TKEEP( BLNK_AXIvideo2Mat_24_480_640_32_U0_InS_TKEEP ),
    .InS_TSTRB( BLNK_AXIvideo2Mat_24_480_640_32_U0_InS_TSTRB ),
    .InS_TUSER( BLNK_AXIvideo2Mat_24_480_640_32_U0_InS_TUSER ),
    .InS_TLAST( BLNK_AXIvideo2Mat_24_480_640_32_U0_InS_TLAST ),
    .InS_TID( BLNK_AXIvideo2Mat_24_480_640_32_U0_InS_TID ),
    .InS_TDEST( BLNK_AXIvideo2Mat_24_480_640_32_U0_InS_TDEST ),
    .img_data_stream_0_V_din( BLNK_AXIvideo2Mat_24_480_640_32_U0_img_data_stream_0_V_din ),
    .img_data_stream_0_V_full_n( BLNK_AXIvideo2Mat_24_480_640_32_U0_img_data_stream_0_V_full_n ),
    .img_data_stream_0_V_write( BLNK_AXIvideo2Mat_24_480_640_32_U0_img_data_stream_0_V_write ),
    .img_data_stream_1_V_din( BLNK_AXIvideo2Mat_24_480_640_32_U0_img_data_stream_1_V_din ),
    .img_data_stream_1_V_full_n( BLNK_AXIvideo2Mat_24_480_640_32_U0_img_data_stream_1_V_full_n ),
    .img_data_stream_1_V_write( BLNK_AXIvideo2Mat_24_480_640_32_U0_img_data_stream_1_V_write ),
    .img_data_stream_2_V_din( BLNK_AXIvideo2Mat_24_480_640_32_U0_img_data_stream_2_V_din ),
    .img_data_stream_2_V_full_n( BLNK_AXIvideo2Mat_24_480_640_32_U0_img_data_stream_2_V_full_n ),
    .img_data_stream_2_V_write( BLNK_AXIvideo2Mat_24_480_640_32_U0_img_data_stream_2_V_write )
);

BLNK_Loop_1_proc BLNK_Loop_1_proc_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( BLNK_Loop_1_proc_U0_ap_start ),
    .ap_done( BLNK_Loop_1_proc_U0_ap_done ),
    .ap_continue( BLNK_Loop_1_proc_U0_ap_continue ),
    .ap_idle( BLNK_Loop_1_proc_U0_ap_idle ),
    .ap_ready( BLNK_Loop_1_proc_U0_ap_ready ),
    .img_0_data_stream_0_V_dout( BLNK_Loop_1_proc_U0_img_0_data_stream_0_V_dout ),
    .img_0_data_stream_0_V_empty_n( BLNK_Loop_1_proc_U0_img_0_data_stream_0_V_empty_n ),
    .img_0_data_stream_0_V_read( BLNK_Loop_1_proc_U0_img_0_data_stream_0_V_read ),
    .img_0_data_stream_1_V_dout( BLNK_Loop_1_proc_U0_img_0_data_stream_1_V_dout ),
    .img_0_data_stream_1_V_empty_n( BLNK_Loop_1_proc_U0_img_0_data_stream_1_V_empty_n ),
    .img_0_data_stream_1_V_read( BLNK_Loop_1_proc_U0_img_0_data_stream_1_V_read ),
    .img_0_data_stream_2_V_dout( BLNK_Loop_1_proc_U0_img_0_data_stream_2_V_dout ),
    .img_0_data_stream_2_V_empty_n( BLNK_Loop_1_proc_U0_img_0_data_stream_2_V_empty_n ),
    .img_0_data_stream_2_V_read( BLNK_Loop_1_proc_U0_img_0_data_stream_2_V_read ),
    .img_1_data_stream_0_V_din( BLNK_Loop_1_proc_U0_img_1_data_stream_0_V_din ),
    .img_1_data_stream_0_V_full_n( BLNK_Loop_1_proc_U0_img_1_data_stream_0_V_full_n ),
    .img_1_data_stream_0_V_write( BLNK_Loop_1_proc_U0_img_1_data_stream_0_V_write ),
    .img_1_data_stream_1_V_din( BLNK_Loop_1_proc_U0_img_1_data_stream_1_V_din ),
    .img_1_data_stream_1_V_full_n( BLNK_Loop_1_proc_U0_img_1_data_stream_1_V_full_n ),
    .img_1_data_stream_1_V_write( BLNK_Loop_1_proc_U0_img_1_data_stream_1_V_write ),
    .img_1_data_stream_2_V_din( BLNK_Loop_1_proc_U0_img_1_data_stream_2_V_din ),
    .img_1_data_stream_2_V_full_n( BLNK_Loop_1_proc_U0_img_1_data_stream_2_V_full_n ),
    .img_1_data_stream_2_V_write( BLNK_Loop_1_proc_U0_img_1_data_stream_2_V_write )
);

BLNK_Mat2AXIvideo_24_480_640_32_s BLNK_Mat2AXIvideo_24_480_640_32_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( BLNK_Mat2AXIvideo_24_480_640_32_U0_ap_start ),
    .ap_done( BLNK_Mat2AXIvideo_24_480_640_32_U0_ap_done ),
    .ap_continue( BLNK_Mat2AXIvideo_24_480_640_32_U0_ap_continue ),
    .ap_idle( BLNK_Mat2AXIvideo_24_480_640_32_U0_ap_idle ),
    .ap_ready( BLNK_Mat2AXIvideo_24_480_640_32_U0_ap_ready ),
    .img_data_stream_0_V_dout( BLNK_Mat2AXIvideo_24_480_640_32_U0_img_data_stream_0_V_dout ),
    .img_data_stream_0_V_empty_n( BLNK_Mat2AXIvideo_24_480_640_32_U0_img_data_stream_0_V_empty_n ),
    .img_data_stream_0_V_read( BLNK_Mat2AXIvideo_24_480_640_32_U0_img_data_stream_0_V_read ),
    .img_data_stream_1_V_dout( BLNK_Mat2AXIvideo_24_480_640_32_U0_img_data_stream_1_V_dout ),
    .img_data_stream_1_V_empty_n( BLNK_Mat2AXIvideo_24_480_640_32_U0_img_data_stream_1_V_empty_n ),
    .img_data_stream_1_V_read( BLNK_Mat2AXIvideo_24_480_640_32_U0_img_data_stream_1_V_read ),
    .img_data_stream_2_V_dout( BLNK_Mat2AXIvideo_24_480_640_32_U0_img_data_stream_2_V_dout ),
    .img_data_stream_2_V_empty_n( BLNK_Mat2AXIvideo_24_480_640_32_U0_img_data_stream_2_V_empty_n ),
    .img_data_stream_2_V_read( BLNK_Mat2AXIvideo_24_480_640_32_U0_img_data_stream_2_V_read ),
    .OutS_TDATA( BLNK_Mat2AXIvideo_24_480_640_32_U0_OutS_TDATA ),
    .OutS_TVALID( BLNK_Mat2AXIvideo_24_480_640_32_U0_OutS_TVALID ),
    .OutS_TREADY( BLNK_Mat2AXIvideo_24_480_640_32_U0_OutS_TREADY ),
    .OutS_TKEEP( BLNK_Mat2AXIvideo_24_480_640_32_U0_OutS_TKEEP ),
    .OutS_TSTRB( BLNK_Mat2AXIvideo_24_480_640_32_U0_OutS_TSTRB ),
    .OutS_TUSER( BLNK_Mat2AXIvideo_24_480_640_32_U0_OutS_TUSER ),
    .OutS_TLAST( BLNK_Mat2AXIvideo_24_480_640_32_U0_OutS_TLAST ),
    .OutS_TID( BLNK_Mat2AXIvideo_24_480_640_32_U0_OutS_TID ),
    .OutS_TDEST( BLNK_Mat2AXIvideo_24_480_640_32_U0_OutS_TDEST )
);

FIFO_BLNK_img_0_data_stream_0_V img_0_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_0_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( img_0_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( img_0_data_stream_0_V_din ),
    .if_full_n( img_0_data_stream_0_V_full_n ),
    .if_write( img_0_data_stream_0_V_write ),
    .if_dout( img_0_data_stream_0_V_dout ),
    .if_empty_n( img_0_data_stream_0_V_empty_n ),
    .if_read( img_0_data_stream_0_V_read )
);

FIFO_BLNK_img_0_data_stream_1_V img_0_data_stream_1_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_0_data_stream_1_V_U_ap_dummy_ce ),
    .if_write_ce( img_0_data_stream_1_V_U_ap_dummy_ce ),
    .if_din( img_0_data_stream_1_V_din ),
    .if_full_n( img_0_data_stream_1_V_full_n ),
    .if_write( img_0_data_stream_1_V_write ),
    .if_dout( img_0_data_stream_1_V_dout ),
    .if_empty_n( img_0_data_stream_1_V_empty_n ),
    .if_read( img_0_data_stream_1_V_read )
);

FIFO_BLNK_img_0_data_stream_2_V img_0_data_stream_2_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_0_data_stream_2_V_U_ap_dummy_ce ),
    .if_write_ce( img_0_data_stream_2_V_U_ap_dummy_ce ),
    .if_din( img_0_data_stream_2_V_din ),
    .if_full_n( img_0_data_stream_2_V_full_n ),
    .if_write( img_0_data_stream_2_V_write ),
    .if_dout( img_0_data_stream_2_V_dout ),
    .if_empty_n( img_0_data_stream_2_V_empty_n ),
    .if_read( img_0_data_stream_2_V_read )
);

FIFO_BLNK_img_1_data_stream_0_V img_1_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_1_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( img_1_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( img_1_data_stream_0_V_din ),
    .if_full_n( img_1_data_stream_0_V_full_n ),
    .if_write( img_1_data_stream_0_V_write ),
    .if_dout( img_1_data_stream_0_V_dout ),
    .if_empty_n( img_1_data_stream_0_V_empty_n ),
    .if_read( img_1_data_stream_0_V_read )
);

FIFO_BLNK_img_1_data_stream_1_V img_1_data_stream_1_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_1_data_stream_1_V_U_ap_dummy_ce ),
    .if_write_ce( img_1_data_stream_1_V_U_ap_dummy_ce ),
    .if_din( img_1_data_stream_1_V_din ),
    .if_full_n( img_1_data_stream_1_V_full_n ),
    .if_write( img_1_data_stream_1_V_write ),
    .if_dout( img_1_data_stream_1_V_dout ),
    .if_empty_n( img_1_data_stream_1_V_empty_n ),
    .if_read( img_1_data_stream_1_V_read )
);

FIFO_BLNK_img_1_data_stream_2_V img_1_data_stream_2_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_1_data_stream_2_V_U_ap_dummy_ce ),
    .if_write_ce( img_1_data_stream_2_V_U_ap_dummy_ce ),
    .if_din( img_1_data_stream_2_V_din ),
    .if_full_n( img_1_data_stream_2_V_full_n ),
    .if_write( img_1_data_stream_2_V_write ),
    .if_dout( img_1_data_stream_2_V_dout ),
    .if_empty_n( img_1_data_stream_2_V_empty_n ),
    .if_read( img_1_data_stream_2_V_read )
);



always @ (posedge ap_clk) begin : ap_ret_BLNK_Loop_1_proc_U0_ap_start
    if (ap_rst_n_inv == 1'b1) begin
        BLNK_Loop_1_proc_U0_ap_start <= ap_const_logic_0;
    end else begin
        BLNK_Loop_1_proc_U0_ap_start <= ap_const_logic_1;
    end
end

always @ (posedge ap_clk) begin : ap_ret_BLNK_Mat2AXIvideo_24_480_640_32_U0_ap_start
    if (ap_rst_n_inv == 1'b1) begin
        BLNK_Mat2AXIvideo_24_480_640_32_U0_ap_start <= ap_const_logic_0;
    end else begin
        BLNK_Mat2AXIvideo_24_480_640_32_U0_ap_start <= ap_const_logic_1;
    end
end

always @ (posedge ap_clk) begin
    ap_CS <= ap_const_logic_0;
end

always @ (BLNK_Mat2AXIvideo_24_480_640_32_U0_ap_done) begin
    if ((ap_const_logic_1 == BLNK_Mat2AXIvideo_24_480_640_32_U0_ap_done)) begin
        ap_sig_hs_done = ap_const_logic_1;
    end else begin
        ap_sig_hs_done = ap_const_logic_0;
    end
end

assign BLNK_AXIvideo2Mat_24_480_640_32_U0_InS_TDATA = InS_TDATA;

assign BLNK_AXIvideo2Mat_24_480_640_32_U0_InS_TDEST = InS_TDEST;

assign BLNK_AXIvideo2Mat_24_480_640_32_U0_InS_TID = InS_TID;

assign BLNK_AXIvideo2Mat_24_480_640_32_U0_InS_TKEEP = InS_TKEEP;

assign BLNK_AXIvideo2Mat_24_480_640_32_U0_InS_TLAST = InS_TLAST;

assign BLNK_AXIvideo2Mat_24_480_640_32_U0_InS_TSTRB = InS_TSTRB;

assign BLNK_AXIvideo2Mat_24_480_640_32_U0_InS_TUSER = InS_TUSER;

assign BLNK_AXIvideo2Mat_24_480_640_32_U0_InS_TVALID = InS_TVALID;

assign BLNK_AXIvideo2Mat_24_480_640_32_U0_ap_continue = ap_const_logic_1;

assign BLNK_AXIvideo2Mat_24_480_640_32_U0_ap_start = ap_const_logic_1;

assign BLNK_AXIvideo2Mat_24_480_640_32_U0_img_data_stream_0_V_full_n = img_0_data_stream_0_V_full_n;

assign BLNK_AXIvideo2Mat_24_480_640_32_U0_img_data_stream_1_V_full_n = img_0_data_stream_1_V_full_n;

assign BLNK_AXIvideo2Mat_24_480_640_32_U0_img_data_stream_2_V_full_n = img_0_data_stream_2_V_full_n;

assign BLNK_Loop_1_proc_U0_ap_continue = ap_const_logic_1;

assign BLNK_Loop_1_proc_U0_img_0_data_stream_0_V_dout = img_0_data_stream_0_V_dout;

assign BLNK_Loop_1_proc_U0_img_0_data_stream_0_V_empty_n = img_0_data_stream_0_V_empty_n;

assign BLNK_Loop_1_proc_U0_img_0_data_stream_1_V_dout = img_0_data_stream_1_V_dout;

assign BLNK_Loop_1_proc_U0_img_0_data_stream_1_V_empty_n = img_0_data_stream_1_V_empty_n;

assign BLNK_Loop_1_proc_U0_img_0_data_stream_2_V_dout = img_0_data_stream_2_V_dout;

assign BLNK_Loop_1_proc_U0_img_0_data_stream_2_V_empty_n = img_0_data_stream_2_V_empty_n;

assign BLNK_Loop_1_proc_U0_img_1_data_stream_0_V_full_n = img_1_data_stream_0_V_full_n;

assign BLNK_Loop_1_proc_U0_img_1_data_stream_1_V_full_n = img_1_data_stream_1_V_full_n;

assign BLNK_Loop_1_proc_U0_img_1_data_stream_2_V_full_n = img_1_data_stream_2_V_full_n;

assign BLNK_Mat2AXIvideo_24_480_640_32_U0_OutS_TREADY = OutS_TREADY;

assign BLNK_Mat2AXIvideo_24_480_640_32_U0_ap_continue = ap_const_logic_1;

assign BLNK_Mat2AXIvideo_24_480_640_32_U0_img_data_stream_0_V_dout = img_1_data_stream_0_V_dout;

assign BLNK_Mat2AXIvideo_24_480_640_32_U0_img_data_stream_0_V_empty_n = img_1_data_stream_0_V_empty_n;

assign BLNK_Mat2AXIvideo_24_480_640_32_U0_img_data_stream_1_V_dout = img_1_data_stream_1_V_dout;

assign BLNK_Mat2AXIvideo_24_480_640_32_U0_img_data_stream_1_V_empty_n = img_1_data_stream_1_V_empty_n;

assign BLNK_Mat2AXIvideo_24_480_640_32_U0_img_data_stream_2_V_dout = img_1_data_stream_2_V_dout;

assign BLNK_Mat2AXIvideo_24_480_640_32_U0_img_data_stream_2_V_empty_n = img_1_data_stream_2_V_empty_n;

assign InS_TREADY = BLNK_AXIvideo2Mat_24_480_640_32_U0_InS_TREADY;

assign OutS_TDATA = BLNK_Mat2AXIvideo_24_480_640_32_U0_OutS_TDATA;

assign OutS_TDEST = BLNK_Mat2AXIvideo_24_480_640_32_U0_OutS_TDEST;

assign OutS_TID = BLNK_Mat2AXIvideo_24_480_640_32_U0_OutS_TID;

assign OutS_TKEEP = BLNK_Mat2AXIvideo_24_480_640_32_U0_OutS_TKEEP;

assign OutS_TLAST = BLNK_Mat2AXIvideo_24_480_640_32_U0_OutS_TLAST;

assign OutS_TSTRB = BLNK_Mat2AXIvideo_24_480_640_32_U0_OutS_TSTRB;

assign OutS_TUSER = BLNK_Mat2AXIvideo_24_480_640_32_U0_OutS_TUSER;

assign OutS_TVALID = BLNK_Mat2AXIvideo_24_480_640_32_U0_OutS_TVALID;


always @ (ap_rst_n) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sig_hs_continue = ap_const_logic_0;

assign img_0_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_0_data_stream_0_V_din = BLNK_AXIvideo2Mat_24_480_640_32_U0_img_data_stream_0_V_din;

assign img_0_data_stream_0_V_read = BLNK_Loop_1_proc_U0_img_0_data_stream_0_V_read;

assign img_0_data_stream_0_V_write = BLNK_AXIvideo2Mat_24_480_640_32_U0_img_data_stream_0_V_write;

assign img_0_data_stream_1_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_0_data_stream_1_V_din = BLNK_AXIvideo2Mat_24_480_640_32_U0_img_data_stream_1_V_din;

assign img_0_data_stream_1_V_read = BLNK_Loop_1_proc_U0_img_0_data_stream_1_V_read;

assign img_0_data_stream_1_V_write = BLNK_AXIvideo2Mat_24_480_640_32_U0_img_data_stream_1_V_write;

assign img_0_data_stream_2_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_0_data_stream_2_V_din = BLNK_AXIvideo2Mat_24_480_640_32_U0_img_data_stream_2_V_din;

assign img_0_data_stream_2_V_read = BLNK_Loop_1_proc_U0_img_0_data_stream_2_V_read;

assign img_0_data_stream_2_V_write = BLNK_AXIvideo2Mat_24_480_640_32_U0_img_data_stream_2_V_write;

assign img_1_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_1_data_stream_0_V_din = BLNK_Loop_1_proc_U0_img_1_data_stream_0_V_din;

assign img_1_data_stream_0_V_read = BLNK_Mat2AXIvideo_24_480_640_32_U0_img_data_stream_0_V_read;

assign img_1_data_stream_0_V_write = BLNK_Loop_1_proc_U0_img_1_data_stream_0_V_write;

assign img_1_data_stream_1_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_1_data_stream_1_V_din = BLNK_Loop_1_proc_U0_img_1_data_stream_1_V_din;

assign img_1_data_stream_1_V_read = BLNK_Mat2AXIvideo_24_480_640_32_U0_img_data_stream_1_V_read;

assign img_1_data_stream_1_V_write = BLNK_Loop_1_proc_U0_img_1_data_stream_1_V_write;

assign img_1_data_stream_2_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_1_data_stream_2_V_din = BLNK_Loop_1_proc_U0_img_1_data_stream_2_V_din;

assign img_1_data_stream_2_V_read = BLNK_Mat2AXIvideo_24_480_640_32_U0_img_data_stream_2_V_read;

assign img_1_data_stream_2_V_write = BLNK_Loop_1_proc_U0_img_1_data_stream_2_V_write;


endmodule //BLNK

