// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module BLNK_AXIvideo2Mat_24_480_640_32_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        InS_TDATA,
        InS_TVALID,
        InS_TREADY,
        InS_TKEEP,
        InS_TSTRB,
        InS_TUSER,
        InS_TLAST,
        InS_TID,
        InS_TDEST,
        img_data_stream_0_V_din,
        img_data_stream_0_V_full_n,
        img_data_stream_0_V_write,
        img_data_stream_1_V_din,
        img_data_stream_1_V_full_n,
        img_data_stream_1_V_write,
        img_data_stream_2_V_din,
        img_data_stream_2_V_full_n,
        img_data_stream_2_V_write
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 7'b1;
parameter    ap_ST_st2_fsm_1 = 7'b10;
parameter    ap_ST_st3_fsm_2 = 7'b100;
parameter    ap_ST_st4_fsm_3 = 7'b1000;
parameter    ap_ST_pp1_stg0_fsm_4 = 7'b10000;
parameter    ap_ST_st7_fsm_5 = 7'b100000;
parameter    ap_ST_st8_fsm_6 = 7'b1000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv9_0 = 9'b000000000;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv9_1E0 = 9'b111100000;
parameter    ap_const_lv9_1 = 9'b1;
parameter    ap_const_lv10_280 = 10'b1010000000;
parameter    ap_const_lv10_1 = 10'b1;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [23:0] InS_TDATA;
input   InS_TVALID;
output   InS_TREADY;
input  [2:0] InS_TKEEP;
input  [2:0] InS_TSTRB;
input  [0:0] InS_TUSER;
input  [0:0] InS_TLAST;
input  [0:0] InS_TID;
input  [0:0] InS_TDEST;
output  [7:0] img_data_stream_0_V_din;
input   img_data_stream_0_V_full_n;
output   img_data_stream_0_V_write;
output  [7:0] img_data_stream_1_V_din;
input   img_data_stream_1_V_full_n;
output   img_data_stream_1_V_write;
output  [7:0] img_data_stream_2_V_din;
input   img_data_stream_2_V_full_n;
output   img_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg InS_TREADY;
reg img_data_stream_0_V_write;
reg img_data_stream_1_V_write;
reg img_data_stream_2_V_write;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm = 7'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_26;
reg   [0:0] eol_1_reg_164;
reg   [23:0] axi_data_V_1_reg_175;
reg   [9:0] p_3_reg_186;
reg   [0:0] eol_reg_197;
reg   [0:0] axi_last_V_2_reg_209;
reg   [23:0] p_Val2_s_reg_222;
reg   [23:0] tmp_data_V_reg_349;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_73;
reg   [0:0] tmp_last_V_reg_357;
wire   [0:0] exitcond3_fu_287_p2;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_bdd_87;
wire   [8:0] i_V_fu_293_p2;
reg   [8:0] i_V_reg_373;
wire   [0:0] exitcond4_fu_299_p2;
reg   [0:0] exitcond4_reg_378;
reg    ap_sig_cseq_ST_pp1_stg0_fsm_4;
reg    ap_sig_bdd_98;
wire   [0:0] brmerge_fu_314_p2;
reg    ap_sig_bdd_106;
reg    ap_reg_ppiten_pp1_it0 = 1'b0;
reg    ap_sig_bdd_119;
reg    ap_reg_ppiten_pp1_it1 = 1'b0;
wire   [9:0] j_V_fu_305_p2;
wire   [7:0] tmp_8_fu_320_p1;
reg   [7:0] tmp_8_reg_391;
reg   [7:0] tmp_5_reg_396;
reg   [7:0] tmp_6_reg_401;
reg    ap_sig_cseq_ST_st7_fsm_5;
reg    ap_sig_bdd_144;
reg    ap_sig_bdd_149;
reg   [0:0] axi_last_V_3_reg_234;
reg   [0:0] axi_last_V1_reg_133;
reg    ap_sig_cseq_ST_st8_fsm_6;
reg    ap_sig_bdd_167;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_174;
reg   [23:0] axi_data_V_3_reg_246;
reg   [23:0] axi_data_V1_reg_143;
reg   [8:0] p_s_reg_153;
reg   [0:0] eol_1_phi_fu_167_p4;
reg   [23:0] axi_data_V_1_phi_fu_178_p4;
reg   [0:0] eol_phi_fu_201_p4;
wire   [0:0] ap_reg_phiprechg_axi_last_V_2_reg_209pp1_it0;
wire   [23:0] ap_reg_phiprechg_p_Val2_s_reg_222pp1_it0;
reg   [23:0] p_Val2_s_phi_fu_226_p4;
reg   [0:0] eol_2_reg_258;
reg   [0:0] sof_1_fu_90;
wire   [0:0] tmp_user_V_fu_278_p1;
reg   [6:0] ap_NS_fsm;
reg    ap_sig_bdd_293;
reg    ap_sig_bdd_105;
reg    ap_sig_bdd_198;
reg    ap_sig_bdd_130;
reg    ap_sig_bdd_213;




always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(exitcond3_fu_287_p2 == ap_const_lv1_0))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp1_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & ~((ap_sig_bdd_106 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_119 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond4_fu_299_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond3_fu_287_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp1_it0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp1_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond4_fu_299_p2 == ap_const_lv1_0) & ~((ap_sig_bdd_106 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_119 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
            ap_reg_ppiten_pp1_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond3_fu_287_p2 == ap_const_lv1_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & ~((ap_sig_bdd_106 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_119 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond4_fu_299_p2 == ap_const_lv1_0)))) begin
            ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        axi_data_V1_reg_143 <= tmp_data_V_reg_349;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_6)) begin
        axi_data_V1_reg_143 <= axi_data_V_3_reg_246;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond4_reg_378 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~((ap_sig_bdd_106 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_119 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        axi_data_V_1_reg_175 <= p_Val2_s_reg_222;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond3_fu_287_p2 == ap_const_lv1_0))) begin
        axi_data_V_1_reg_175 <= axi_data_V1_reg_143;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_106 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_119 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond4_fu_299_p2 == ap_const_lv1_0))) begin
        axi_data_V_3_reg_246 <= axi_data_V_1_phi_fu_178_p4;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_5) & (ap_const_lv1_0 == eol_2_reg_258) & ~ap_sig_bdd_149)) begin
        axi_data_V_3_reg_246 <= InS_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        axi_last_V1_reg_133 <= tmp_last_V_reg_357;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_6)) begin
        axi_last_V1_reg_133 <= axi_last_V_3_reg_234;
    end
end

always @ (posedge ap_clk) begin
    if (ap_sig_bdd_130) begin
        if (ap_sig_bdd_198) begin
            axi_last_V_2_reg_209 <= eol_1_phi_fu_167_p4;
        end else if (ap_sig_bdd_105) begin
            axi_last_V_2_reg_209 <= InS_TLAST;
        end else if ((ap_true == ap_true)) begin
            axi_last_V_2_reg_209 <= ap_reg_phiprechg_axi_last_V_2_reg_209pp1_it0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_106 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_119 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond4_fu_299_p2 == ap_const_lv1_0))) begin
        axi_last_V_3_reg_234 <= eol_1_phi_fu_167_p4;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_5) & (ap_const_lv1_0 == eol_2_reg_258) & ~ap_sig_bdd_149)) begin
        axi_last_V_3_reg_234 <= InS_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond4_reg_378 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~((ap_sig_bdd_106 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_119 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        eol_1_reg_164 <= axi_last_V_2_reg_209;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond3_fu_287_p2 == ap_const_lv1_0))) begin
        eol_1_reg_164 <= axi_last_V1_reg_133;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_106 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_119 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond4_fu_299_p2 == ap_const_lv1_0))) begin
        eol_2_reg_258 <= eol_phi_fu_201_p4;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_5) & (ap_const_lv1_0 == eol_2_reg_258) & ~ap_sig_bdd_149)) begin
        eol_2_reg_258 <= InS_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond4_reg_378 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~((ap_sig_bdd_106 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_119 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        eol_reg_197 <= axi_last_V_2_reg_209;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond3_fu_287_p2 == ap_const_lv1_0))) begin
        eol_reg_197 <= ap_const_lv1_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond4_fu_299_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_106 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_119 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        p_3_reg_186 <= j_V_fu_305_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond3_fu_287_p2 == ap_const_lv1_0))) begin
        p_3_reg_186 <= ap_const_lv10_0;
    end
end

always @ (posedge ap_clk) begin
    if (ap_sig_bdd_130) begin
        if (ap_sig_bdd_198) begin
            p_Val2_s_reg_222 <= axi_data_V_1_phi_fu_178_p4;
        end else if (ap_sig_bdd_105) begin
            p_Val2_s_reg_222 <= InS_TDATA;
        end else if ((ap_true == ap_true)) begin
            p_Val2_s_reg_222 <= ap_reg_phiprechg_p_Val2_s_reg_222pp1_it0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        p_s_reg_153 <= ap_const_lv9_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_6)) begin
        p_s_reg_153 <= i_V_reg_373;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond4_fu_299_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_106 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_119 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        sof_1_fu_90 <= ap_const_lv1_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        sof_1_fu_90 <= ap_const_lv1_1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & ~((ap_sig_bdd_106 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_119 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        exitcond4_reg_378 <= exitcond4_fu_299_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        i_V_reg_373 <= i_V_fu_293_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond4_fu_299_p2 == ap_const_lv1_0) & ~((ap_sig_bdd_106 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_119 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        tmp_5_reg_396 <= {{p_Val2_s_phi_fu_226_p4[ap_const_lv32_F : ap_const_lv32_8]}};
        tmp_6_reg_401 <= {{p_Val2_s_phi_fu_226_p4[ap_const_lv32_17 : ap_const_lv32_10]}};
        tmp_8_reg_391 <= tmp_8_fu_320_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(InS_TVALID == ap_const_logic_0))) begin
        tmp_data_V_reg_349 <= InS_TDATA;
        tmp_last_V_reg_357 <= InS_TLAST;
    end
end

always @ (InS_TVALID or ap_sig_cseq_ST_st2_fsm_1 or exitcond4_fu_299_p2 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or brmerge_fu_314_p2 or ap_sig_bdd_106 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_119 or ap_reg_ppiten_pp1_it1 or ap_sig_cseq_ST_st7_fsm_5 or ap_sig_bdd_149 or eol_2_reg_258) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(InS_TVALID == ap_const_logic_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_5) & (ap_const_lv1_0 == eol_2_reg_258) & ~ap_sig_bdd_149) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond4_fu_299_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == brmerge_fu_314_p2) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_106 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_119 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))))) begin
        InS_TREADY = ap_const_logic_1;
    end else begin
        InS_TREADY = ap_const_logic_0;
    end
end

always @ (ap_done_reg or exitcond3_fu_287_p2 or ap_sig_cseq_ST_st4_fsm_3) begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(exitcond3_fu_287_p2 == ap_const_lv1_0)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (exitcond3_fu_287_p2 or ap_sig_cseq_ST_st4_fsm_3) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(exitcond3_fu_287_p2 == ap_const_lv1_0))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_98) begin
    if (ap_sig_bdd_98) begin
        ap_sig_cseq_ST_pp1_stg0_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp1_stg0_fsm_4 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_26) begin
    if (ap_sig_bdd_26) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_73) begin
    if (ap_sig_bdd_73) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_174) begin
    if (ap_sig_bdd_174) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_87) begin
    if (ap_sig_bdd_87) begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_144) begin
    if (ap_sig_bdd_144) begin
        ap_sig_cseq_ST_st7_fsm_5 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_5 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_167) begin
    if (ap_sig_bdd_167) begin
        ap_sig_cseq_ST_st8_fsm_6 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_6 = ap_const_logic_0;
    end
end

always @ (axi_data_V_1_reg_175 or p_Val2_s_reg_222 or exitcond4_reg_378 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_reg_ppiten_pp1_it1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond4_reg_378 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) begin
        axi_data_V_1_phi_fu_178_p4 = p_Val2_s_reg_222;
    end else begin
        axi_data_V_1_phi_fu_178_p4 = axi_data_V_1_reg_175;
    end
end

always @ (eol_1_reg_164 or axi_last_V_2_reg_209 or exitcond4_reg_378 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_reg_ppiten_pp1_it1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond4_reg_378 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) begin
        eol_1_phi_fu_167_p4 = axi_last_V_2_reg_209;
    end else begin
        eol_1_phi_fu_167_p4 = eol_1_reg_164;
    end
end

always @ (eol_reg_197 or axi_last_V_2_reg_209 or exitcond4_reg_378 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_reg_ppiten_pp1_it1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond4_reg_378 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) begin
        eol_phi_fu_201_p4 = axi_last_V_2_reg_209;
    end else begin
        eol_phi_fu_201_p4 = eol_reg_197;
    end
end

always @ (exitcond4_reg_378 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_sig_bdd_106 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_119 or ap_reg_ppiten_pp1_it1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond4_reg_378 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~((ap_sig_bdd_106 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_119 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        img_data_stream_0_V_write = ap_const_logic_1;
    end else begin
        img_data_stream_0_V_write = ap_const_logic_0;
    end
end

always @ (exitcond4_reg_378 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_sig_bdd_106 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_119 or ap_reg_ppiten_pp1_it1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond4_reg_378 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~((ap_sig_bdd_106 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_119 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        img_data_stream_1_V_write = ap_const_logic_1;
    end else begin
        img_data_stream_1_V_write = ap_const_logic_0;
    end
end

always @ (exitcond4_reg_378 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_sig_bdd_106 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_119 or ap_reg_ppiten_pp1_it1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond4_reg_378 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~((ap_sig_bdd_106 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_119 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        img_data_stream_2_V_write = ap_const_logic_1;
    end else begin
        img_data_stream_2_V_write = ap_const_logic_0;
    end
end

always @ (InS_TDATA or brmerge_fu_314_p2 or axi_data_V_1_phi_fu_178_p4 or ap_reg_phiprechg_p_Val2_s_reg_222pp1_it0 or ap_sig_bdd_213) begin
    if (ap_sig_bdd_213) begin
        if (~(ap_const_lv1_0 == brmerge_fu_314_p2)) begin
            p_Val2_s_phi_fu_226_p4 = axi_data_V_1_phi_fu_178_p4;
        end else if ((ap_const_lv1_0 == brmerge_fu_314_p2)) begin
            p_Val2_s_phi_fu_226_p4 = InS_TDATA;
        end else begin
            p_Val2_s_phi_fu_226_p4 = ap_reg_phiprechg_p_Val2_s_reg_222pp1_it0;
        end
    end else begin
        p_Val2_s_phi_fu_226_p4 = ap_reg_phiprechg_p_Val2_s_reg_222pp1_it0;
    end
end
always @ (ap_CS_fsm or InS_TVALID or exitcond3_fu_287_p2 or exitcond4_fu_299_p2 or ap_sig_bdd_106 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_119 or ap_reg_ppiten_pp1_it1 or ap_sig_bdd_149 or eol_2_reg_258 or tmp_user_V_fu_278_p1 or ap_sig_bdd_293) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~ap_sig_bdd_293) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if ((~(InS_TVALID == ap_const_logic_0) & (ap_const_lv1_0 == tmp_user_V_fu_278_p1))) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else if ((~(InS_TVALID == ap_const_logic_0) & ~(ap_const_lv1_0 == tmp_user_V_fu_278_p1))) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st3_fsm_2 : 
        begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        ap_ST_st4_fsm_3 : 
        begin
            if (~(exitcond3_fu_287_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            end
        end
        ap_ST_pp1_stg0_fsm_4 : 
        begin
            if (~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_106 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_119 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond4_fu_299_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_106 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_119 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond4_fu_299_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_st7_fsm_5;
            end else begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            end
        end
        ap_ST_st7_fsm_5 : 
        begin
            if (((ap_const_lv1_0 == eol_2_reg_258) & ~ap_sig_bdd_149)) begin
                ap_NS_fsm = ap_ST_st7_fsm_5;
            end else if ((~ap_sig_bdd_149 & ~(ap_const_lv1_0 == eol_2_reg_258))) begin
                ap_NS_fsm = ap_ST_st8_fsm_6;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_5;
            end
        end
        ap_ST_st8_fsm_6 : 
        begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end


assign ap_reg_phiprechg_axi_last_V_2_reg_209pp1_it0 = 'bx;

assign ap_reg_phiprechg_p_Val2_s_reg_222pp1_it0 = 'bx;


always @ (exitcond4_fu_299_p2 or brmerge_fu_314_p2) begin
    ap_sig_bdd_105 = ((exitcond4_fu_299_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == brmerge_fu_314_p2));
end


always @ (InS_TVALID or exitcond4_fu_299_p2 or brmerge_fu_314_p2) begin
    ap_sig_bdd_106 = ((InS_TVALID == ap_const_logic_0) & (exitcond4_fu_299_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == brmerge_fu_314_p2));
end


always @ (img_data_stream_0_V_full_n or img_data_stream_1_V_full_n or img_data_stream_2_V_full_n or exitcond4_reg_378) begin
    ap_sig_bdd_119 = (((img_data_stream_0_V_full_n == ap_const_logic_0) & (exitcond4_reg_378 == ap_const_lv1_0)) | ((exitcond4_reg_378 == ap_const_lv1_0) & (img_data_stream_1_V_full_n == ap_const_logic_0)) | ((exitcond4_reg_378 == ap_const_lv1_0) & (img_data_stream_2_V_full_n == ap_const_logic_0)));
end


always @ (ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_sig_bdd_106 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_119 or ap_reg_ppiten_pp1_it1) begin
    ap_sig_bdd_130 = ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_106 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_119 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_144 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_5]);
end


always @ (InS_TVALID or eol_2_reg_258) begin
    ap_sig_bdd_149 = ((InS_TVALID == ap_const_logic_0) & (ap_const_lv1_0 == eol_2_reg_258));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_167 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_6]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_174 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end


always @ (exitcond4_fu_299_p2 or brmerge_fu_314_p2) begin
    ap_sig_bdd_198 = ((exitcond4_fu_299_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == brmerge_fu_314_p2));
end


always @ (exitcond4_fu_299_p2 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_reg_ppiten_pp1_it0) begin
    ap_sig_bdd_213 = ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond4_fu_299_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_26 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end


always @ (ap_start or ap_done_reg) begin
    ap_sig_bdd_293 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_73 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_87 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_98 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end

assign brmerge_fu_314_p2 = (sof_1_fu_90 | eol_phi_fu_201_p4);

assign exitcond3_fu_287_p2 = (p_s_reg_153 == ap_const_lv9_1E0? 1'b1: 1'b0);

assign exitcond4_fu_299_p2 = (p_3_reg_186 == ap_const_lv10_280? 1'b1: 1'b0);

assign i_V_fu_293_p2 = (p_s_reg_153 + ap_const_lv9_1);

assign img_data_stream_0_V_din = tmp_8_reg_391;

assign img_data_stream_1_V_din = tmp_5_reg_396;

assign img_data_stream_2_V_din = tmp_6_reg_401;

assign j_V_fu_305_p2 = (p_3_reg_186 + ap_const_lv10_1);

assign tmp_8_fu_320_p1 = p_Val2_s_phi_fu_226_p4[7:0];

assign tmp_user_V_fu_278_p1 = InS_TUSER;


endmodule //BLNK_AXIvideo2Mat_24_480_640_32_s

