webtalk_init -webtalk_dir C:/Master/FPGA/ejercicios/EC32/FIFO/FIFO.sim/sim_1/behav/xsim/xsim.dir/FIFO_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jan 22 21:49:18 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6dff14a625b0566c803ecb055dd1ef96" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f8445598caae4aecb4d272b97e8a5a84" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "22" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "230 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.30_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9356_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3636753615 -regid "" -xml C:/Master/FPGA/ejercicios/EC32/FIFO/FIFO.sim/sim_1/behav/xsim/xsim.dir/FIFO_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Master/FPGA/ejercicios/EC32/FIFO/FIFO.sim/sim_1/behav/xsim/xsim.dir/FIFO_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Master/FPGA/ejercicios/EC32/FIFO/FIFO.sim/sim_1/behav/xsim/xsim.dir/FIFO_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
